version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - music-library-network
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
      - ${STUDIO_PORT}:${STUDIO_PORT}
    depends_on:
      - db
    restart: always
  db:
    container_name: db
    build:
      context: ./database
      dockerfile: Dockerfile
    networks:
      - music-library-network
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglogs:/var/log/postgresql
    restart: always

networks:
  music-library-network:
    driver: bridge

volumes:
  pgdata:
  pglogs:
